### ISSUE TITLE
Fix broken tests in dlock

### ISSUE THREAD

**Issue by hanzei** [lieut-data/mattermost-plugin-api#30]
All tests in `dlock` are running in an endless loop.

@ilgooz any idea why this is happening?

**Comment by hanzei** [comment]
FYI: This is happening before and after https://github.com/lieut-data/mattermost-plugin-api/pull/31

**Comment by hanzei** [comment]
Somehow is was broken in https://github.com/lieut-data/mattermost-plugin-api/commit/c574cdd05be1b36b3984c120316da4a01c5b6e8f

**Comment by ilgooz** [comment]
Thanks Ben. I will try to take a look! A bit busy these days.

**Comment by hanzei** [comment]
Sure, there is not hurry. Thanks for looking into this :+1:

**Comment by hanzei** [comment]
@lieut-data fixed this in https://github.com/lieut-data/mattermost-plugin-api/commit/3ffb8392917af674c7fe0b47477259433b9211f6.

**Comment by hanzei** [comment]
Still, thanks for looking into it @ilgooz
